services:
  db:
    image: mysql:8.0
    container_name: diseasenet-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: diseasenet
      MYSQL_USER: diseasenet_user
      MYSQL_PASSWORD: diseasenet_pass
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
